### ISSUE TITLE
Misskey v12対応

### ISSUE THREAD

**Issue by fu-sen** [uboar/missli#4]
Calckey’（Misskey v12 派生）の日本インスタンスも生まれたのですが、
calckey.jp でアカウント登録を試したところ、エラーで追加できませんでした。
今後インスタンスが増えそうなので、対応していただけると良さそうです。
よろしくお願いいたします。

**Comment by uboar** [comment]
ありがとうございます！当方でCalckeyのドキュメントや仕様などを読み込めていないので、検証など含め少し時間がかかるかもしれません。

**Comment by ThatOneCalculator** [comment]
https://calckey.jp/api-doc

It's almost the same as Misskey v12.

**Comment by uboar** [comment]
Misskey v12のAPIと互換性が無さそうなので、Issueの名前をv12対応に替えて調査してみます。

**Comment by ThatOneCalculator** [comment]
Calckey also has unique features (Recommended TL, account migration, OCR image captioning API, etc) that would be nice to be seen integrated.

**Comment by fu-sen** [comment]
ThatOneCalculator さん、Calckey の開発者本人です。

@ThatOneCalculator I'm glad you spotted me here so quickly. Let's increase the support of Calckey.

**Comment by fu-sen** [comment]
Misskey v12 のインスタンスを維持しているところもいくつか見られますので、そのインスタンスでも有益ですね。
There are still Misskey. v12 instances in Japan.

**Comment by uboar** [comment]
ローカルでv12のインスタンスを建ててみて検証した所、`/emojis`のAPIエンドポイントが存在しない為エラーが発生するようです。カスタム絵文字の読み込みを一時的に切った所動きました。

I verified this by building a local instance of v12, and it seems that the error occurs because the API endpoint for `/emojis` does not exist. I temporarily turned off the loading of custom emoji and it worked.

<img width="181" alt="image" src="https://user-images.githubusercontent.com/10250330/222682221-7109b0ea-c664-4cf2-93b1-21b906e635af.png">

ひとまず暫定対応として、カスタム絵文字の読み込みに失敗しても処理を続行するようにします。v12系のインスタンスではローカルのカスタム絵文字が表示されません。

For the time being, as a temporary measure, we will continue processing even if loading of custom pictograms fails. v12 series instances will not display local custom pictograms.

v12のAPI仕様まだ詳しく見れていないのですが、APIコンソールから調べた所`admin/emoji/list`（実行にモデレーター権限が必要）以外でカスタム絵文字の一覧を取得する方法を探しています。。。

I haven't had a chance to look at the v12 API spec in detail yet, but I'm looking for a way to get a list of custom emoji other than `admin/emoji/list` (requires moderator privileges to run), which I found from the API console.

**Comment by fu-sen** [comment]
はい。カスタム絵文字はv12 と v13 で API 仕様が変わっている部分です。
Yes. Custom Emoji is the part where the API specification has changed between v12 and v13.

**Comment by uboar** [comment]
ひとまず、[1.0.2](https://github.com/uboar/missli/releases/tag/1.0.2)リリースで暫定対応を実施しています。

**Comment by fu-sen** [comment]
確認してみましたが、Misskey v12・Calckey 共にタイムラインを追加して全く表示されていないようですな～

**Comment by uboar** [comment]
[1.0.21](https://github.com/uboar/missli/releases/tag/1.0.21)リリース、submarineでのTL表示を確認しました。

v12系、フォークの種類によってノートのレスポンス内容に差がありそうなのでうまい具合に落とし所を見つけないといけませんね…

**Comment by fu-sen** [comment]
Calckey も動作しました。大丈夫そうですね！ ありがとうございます～
https://calckey.jp/notes/9bw4tdh1jt

それでは解決という事で issue 閉じます。ありがとうございました～
